
name: Python Tests

on:
  pull_request:
  workflow_dispatch:  # allow running tests via github ui button

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04  # pinned to 20 as 22 was lacking geckodriver

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Run Tests
      env:
        ZEIT_PREMIUM_USER: ${{ secrets.ZEIT_PREMIUM_USER }}
        ZEIT_PREMIUM_PASSWORD: ${{ secrets.ZEIT_PREMIUM_PASSWORD }}
        TOLINO_USER: ${{ secrets.TOLINO_USER }}
        TOLINO_PASSWORD: ${{ secrets.TOLINO_PASSWORD }}
        TOLINO_PARTNER_SHOP: ${{ secrets.TOLINO_PARTNER_SHOP }}
      run: poetry run pytest tests/ -vv --color=yes
